version: '3.8'
services:
  web:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pacientes
      - SECRET_KEY=change_me
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pacientes
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
